### ISSUE TITLE
tap-oracle transforms not working with Pipelinewise

### ISSUE THREAD

**Issue by johnoscott** [transferwise/pipelinewise-transform-field#9]
I have been unable to get Pipelinewise *transformations* working for *tap-oracle*. I have tried all the combinations of replication_method: INCREMENTAL | LOG_BASED and i always get a `KeyError: '<COLUMN_NAME>'.` error in the log. If I remove the transformations config from the tap.yml the sync works fine.

Here is a snippet of the tap.yml
```
schemas:
  - source_schema: "MYSCHEMA"
    target_schema: "DEV_TEST"
    tables:
      - table_name: "TBLINSTITUTION"
        replication_method: "LOG_BASED"
        transformations:
          - column: "ADDRESS1"
            type: "SET-NULL"
```

Here is the error log
```INFO Selected streams: ['MYSCHEMA-TBLINSTITUTION'] 
INFO No currently_syncing found
INFO Beginning sync of stream(MYSCHEMA-TBLINSTITUTION) with sync method(incremental)
INFO Stream MYSCHEMA-TBLINSTITUTION is using incremental replication with replication key CHANGEDDATE
INFO dsn: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=X.X.X.X)(PORT=1521))(CONNECT_DATA=(SID=XXXX)))
INFO Getting catalog objects from information_schema cache table...
INFO select SELECT  "ABBREVIATION" , "ADDRESS1" , "ADDRESS2" , "ADDRESS3" , "ADDRSTATE" , "BILLINGEMAIL" ,to_char( "CHANGEDDATE" ), "CHANGEDUID" , "COUNTRYCODE" , "COURSESURL" ,to_char( "CREATEDDATE" ), "CREATEDUID"  
                                FROM MYSCHEMA.TBLINSTITUTION
                               ORDER BY CHANGEDDATE ASC
                               
CRITICAL 'TBLINSTITUTION'
Traceback (most recent call last):
  File "/app/.virtualenvs/transform-field/bin/transform-field", line 11, in <module>
    load_entry_point('pipelinewise-transform-field==1.0.1', 'console_scripts', 'transform-field')()
  File "/app/.virtualenvs/transform-field/lib/python3.7/site-packages/transform_field/__init__.py", line 235, in main
    raise exc
  File "/app/.virtualenvs/transform-field/lib/python3.7/site-packages/transform_field/__init__.py", line 227, in main
    main_impl()
  File "/app/.virtualenvs/transform-field/lib/python3.7/site-packages/transform_field/__init__.py", line 221, in main_impl
    TransformField(trans_config).consume(reader)
  File "/app/.virtualenvs/transform-field/lib/python3.7/site-packages/transform_field/__init__.py", line 213, in consume
    self.handle_line(line)
  File "/app/.virtualenvs/transform-field/lib/python3.7/site-packages/transform_field/__init__.py", line 192, in handle_line
    self.flush()
  File "/app/.virtualenvs/transform-field/lib/python3.7/site-packages/transform_field/__init__.py", line 91, in flush
    stream_meta = self.stream_meta[stream]
KeyError: 'TBLINSTITUTION'
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 19, "tags": {}}
CRITICAL [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/app/.virtualenvs/tap-oracle/bin/tap-oracle", line 11, in <module>
    load_entry_point('pipelinewise-tap-oracle==1.0.0', 'console_scripts', 'tap-oracle')()
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/__init__.py", line 565, in main
    raise exc
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/__init__.py", line 562, in main
    main_impl()
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/__init__.py", line 556, in main_impl
    do_sync(conn_config, args.catalog, args.config.get('default_replication_method'), state)
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/__init__.py", line 533, in do_sync
    state = sync_traditional_stream(conn_config, stream, state, sync_method_lookup[stream.tap_stream_id], end_scn)
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/__init__.py", line 488, in sync_traditional_stream
    state = do_sync_incremental(conn_config, stream, state, desired_columns)
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/__init__.py", line 374, in do_sync_incremental
    state = incremental.sync_table(conn_config, stream, state, desired_columns)
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/sync_strategies/incremental.py", line 91, in sync_table
    singer.write_message(record_message)
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/singer/messages.py", line 218, in write_message
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
INFO Schema 'DEV_TEST' does not exist. Creating... CREATE SCHEMA IF NOT EXISTS DEV_TEST
INFO Table 'DEV_TEST.tblinstitution' does not exist. Creating...
```

**Comment by koszti** [comment]
interesting, in the YAML the source schema is APPLYOL but the select is using different schema: MYSCHEMA.TBLINSTITUTION

wondering why it’s happening. Do you have the same table in multiple schema?

**Comment by johnoscott** [comment]
Sorry that was a typo. Schema is MYSCHEMA (i corrected the issue above)

**Comment by mpcarter** [comment]
Same thing happened to me just now.

**Comment by mpcarter** [comment]
@johnoscott FYI
https://github.com/transferwise/pipelinewise-tap-oracle/issues/1

**Comment by koszti** [comment]
fixed by https://github.com/transferwise/pipelinewise-tap-oracle/pull/2
